* B
  - Blog
    - [[file:articles/quantum_of_verification.org::#quantum-collaboration-the-observer-effect-damagebdd-s-pioneering-approach-to-software-behaviour-verification][IntroductioN]]
* I
  - [[file:articles/quantum_of_verification.org::#quantum-collaboration-the-observer-effect-damagebdd-s-pioneering-approach-to-software-behaviour-verification][Introduction]]
* W
  - [[file:articles/whatisdamage.org::#what-is-the-function-of-damage-in-the-context-of-software-engineering][What is Damage?]]
